### ISSUE TITLE
Specifying multiple files inside src options

### ISSUE THREAD

**Issue by cheeyeo** [testdouble/grunt-asset-fingerprint#8]
When specifying an array inside src options it only processes the first file in the array?

**Comment by denodster** [comment]
@searls This last comment here should be your documentation instead of what is in Readme.md I spent hours over the last few days trying to figure out how this worked as I was looking at our lineman set up (particularly since asset fingerprinting isn't mentioned on linemanjs.com) and this comment is what finally made everything fit together.

**Comment by denodster** [comment]
I've opened a PR: #10

**Comment by searls** [comment]
sorry that you wasted any time @denodster! thanks for the PR.
